name: device
description: Device & package info which help you store data into backend server
version: 1.0.0
homepage: https://github.com/hsul4n/flutter-packages/tree/main/packages/device

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
