name: attribute_localizations
description: Attribute localizations.
version: 1.0.5
homepage: https://github.com/hsul4n/flutter-packages

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
