name: attribute_localizations
description: Attribute localizations.
version: 1.0.1
homepage: https://github.com/hsul4n/flutter-packages

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
