name: validation_localizations
description: Validation localizations.
version: 1.0.9
homepage: https://github.com/hsul4n/flutter-packages

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  attribute_localizations: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
