name: clip
description: We make picking images more easy.
version: 1.3.2
homepage: https://github.com/hsul4n/flutter-packages

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  flutter_cache_manager: ^3.3.0
