name: clip
description: We make picking images more easy.
version: 1.3.1
homepage: https://github.com/hsul4n/flutter-packages

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  test: ^1.5.1
